<a href="https://colab.research.google.com/github/Ahmad3752/Colab/blob/main/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
df=pd.read_csv("/content/survey_results_public.csv")
df.head()
df.shape

(949, 85)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6607 entries, 0 to 6606
Data columns (total 85 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Respondent              6607 non-null   int64
 1   MainBranch              6607 non-null   object
 2   Hobbyist                6607 non-null   object
 3   OpenSourcer             6607 non-null   object
 4   OpenSource              6470 non-null   object
 5   Employment              6491 non-null   object
 6   Country                 6606 non-null   object
 7   Student                 6479 non-null   object
 8   EdLevel                 6423 non-null   object
 9   UndergradMajor          5607 non-null   object
 10  EduOther                6300 non-null   object
 11  OrgSize                 5362 non-null   object
 12  DevType                 6067 non-null   object
 13  YearsCode               6564 non-null   object
 14  Age1stCode              6529 non-null   object
 15  YearsCodePro            5524 non-null   object
 16  CareerSat               5426 non-null   object
 17  JobSat                  5303 non-null   object
 18  MgrIdiot                4536 non-null   object
 19  MgrMoney                4541 non-null   object
 20  MgrWant                 4543 non-null   object
 21  JobSeek                 6018 non-null   object
 22  LastHireDate            5968 non-null   object
 23  LastInt                 5003 non-null   object
 24  FizzBuzz                5327 non-null   object
 25  JobFactors              5927 non-null   object
 26  ResumeUpdate            5812 non-null   object
 27  CurrencySymbol          5332 non-null   object
 28  CurrencyDesc            5332 non-null   object
 29  CompTotal               4175 non-null   float64
 30  CompFreq                4733 non-null   object
 31  ConvertedComp           4166 non-null   float64
 32  WorkWeekHrs             4798 non-null   float64
 33  WorkPlan                5145 non-null   object
 34  WorkChallenge           5086 non-null   object
 35  WorkRemote              5247 non-null   object
 36  WorkLoc                 5240 non-null   object
 37  ImpSyn                  5341 non-null   object
 38  CodeRev                 5252 non-null   object
 39  CodeRevHrs              3730 non-null   float64
 40  UnitTests               4693 non-null   object
 41  PurchaseHow             4563 non-null   object
 42  PurchaseWhat            4638 non-null   object
 43  LanguageWorkedWith      6535 non-null   object
 44  LanguageDesireNextYear  6265 non-null   object
 45  DatabaseWorkedWith      5669 non-null   object
 46  DatabaseDesireNextYear  5170 non-null   object
 47  PlatformWorkedWith      6014 non-null   object
 48  PlatformDesireNextYear  5795 non-null   object
 49  WebFrameWorkedWith      4889 non-null   object
 50  WebFrameDesireNextYear  4753 non-null   object
 51  MiscTechWorkedWith      4446 non-null   object
 52  MiscTechDesireNextYear  4887 non-null   object
 53  DevEnviron              6513 non-null   object
 54  OpSys                   6555 non-null   object
 55  Containers              6392 non-null   object
 56  BlockchainOrg           3641 non-null   object
 57  BlockchainIs            4534 non-null   object
 58  BetterLife              6419 non-null   object
 59  ITperson                6482 non-null   object
 60  OffOn                   6447 non-null   object
 61  SocialMedia             6316 non-null   object
 62  Extraversion            6499 non-null   object
 63  ScreenName              5992 non-null   object
 64  SOVisit1st              6263 non-null   object
 65  SOVisitFreq             6576 non-null   object
 66  SOVisitTo               6562 non-null   object
 67  SOFindAnswer            6538 non-null   object
 68  SOTimeSaved             6440 non-null   object
 69  SOHowMuchTime           5124 non-null   object
 70  SOAccount               6553 non-null   object
 71  SOPartFreq              5564 non-null   object
 72  SOJobs                  6560 non-null   object
 73  EntTeams                6537 non-null   object
 74  SOComm                  6567 non-null   object
 75  WelcomeChange           6373 non-null   object
 76  SONewContent            5164 non-null   object
 77  Age                     5893 non-null   float64
 78  Gender                  6353 non-null   object
 79  Trans                   6233 non-null   object
 80  Sexuality               5705 non-null   object
 81  Ethnicity               5676 non-null   object
 82  Dependents              6184 non-null   object
 83  SurveyLength            6474 non-null   object
 84  SurveyEase              6487 non-null   object
dtypes: float64(5), int64(1), object(79)
memory usage: 4.3+ MB

In [ ]:
df[['Country','Student']].iloc[0:2,0]
#iloc is integer based indexing iloc[row,column] both rows and columns should be integer
df[['Country','Student']].loc[0:2] # ab loc mai row toh hai integer but column cant be
#Selection Type	.loc[] (Label-based)	                        .iloc[] (Integer-based)
#Row Selection	Can be integers (if the index is numeric)	c       Must be integers
#Column Selection	Must be column names ❌	                      Must be integers ✅

                  Country         Student
0          United Kingdom              No
1  Bosnia and Herzegovina  Yes, full-time
2                Thailand              No

In [ ]:
df['Hobbyist'].value_counts()

Hobbyist
Yes    5361
No     1246
Name: count, dtype: int64

In [ ]:
df.loc[0:2,'Hobbyist':'Employment']# semi colon k liye double brackets nahi lagathe
df.loc[0:2,['Hobbyist','Employment']]
df.loc[[0,2],['Hobbyist','Employment']]

  Hobbyist                              Employment
0      Yes  Not employed, and not looking for work
2      Yes                      Employed full-time

In [ ]:
##Customing Indexes
import pandas as pd

# Creating the dictionary
data = {
    "First Name": ["Ali", "Sara", "John", "Aisha"],
    "Last Name": ["Khan", "Ahmed", "Doe", "Rehman"],
    "email": ["ali.khan@example.com", "sara.ahmed@example.com", "john.doe@example.com", "aisha.rehman@example.com"]
}

# Converting to DataFrame
df1 = pd.DataFrame(data)

# Displaying the DataFrame
#df1.set_index('email',inplace=True)
#df1.sort_index()## if descending so ascending =false

In [ ]:
df1.loc['ali.khan@example.com']#acha ab index email hai toh ab hum row mai integers nahi use karsakthe o sirf thab jab index serial no ho

KeyError: 'ali.khan@example.com'

In [ ]:
import pandas as pd
df=pd.read_csv("/content/survey_results_public.csv",index_col='Respondent')
df.head()

In [ ]:
df.isna().sum()

In [ ]:
#Filtering data

#****Imp***********
#1)FOR LIST WE USE ISIN  countries=['United States','India']  filt1=df['Country'].isin(countries)
#2)AGAR KOYI COLUMN STRING HAITOH .STR.CONTAINS PYTHON YA KIYA MATLAB JO CHECK KARNA HAI
#3) .LOC METHOD BARHA FAIDE KA DF.LOC[FILT,OR JO COLUMNS CHAHIYE]

import pandas as pd
df=pd.read_csv("/content/survey_results_public.csv")
#filt=(df['last']=='Doe')
#df[filt]
#filt=df['ConvertedComp']>1000
#df[filt]      acha ab idhar loc ka apna maza hai  q k dekho o specific column b leke detha hai
#df.loc[filt,['Student', 'LanguageWorkedWith','Country']]
#Now i want that they should only be from 2 countries

countries=['United States','India']
filt1=df['Country'].isin(countries) # to check in list is countries
df[filt1]

#acha ab misal k tor languages worked with column 1 string hai or hume check karna hai k us k anadr python hai so contain
filt=df['LanguageWorkedWith'].str.contains('Python',na=False)#ab is mai kafi null values hai toh so tackling with it k liye na=False kar diya
df.loc[filt].head(2)

In [ ]:
#Modifying updating rows and columns

#changing all columns
df1.columns=['first_name','last_name','email']
df1.columns=[x.upper() for x in df1.columns]
df1.columns=df1.columns.str.replace('_',' ') #df1.columns=[x.replace(' ','_') for x in df1.columns]
#changing specific columns
df1.rename(columns={'FIRST NAME':'first'},inplace=True)
df1

1)Acha ab suno jab b key vlaue change karna ho toh replace use karo as it is good for changing jab k map jo hai o bakiyo ko NAN SET KARTHA HAI
2)Apply: it is used for series
3)Apply map: for data frame
SORTCUT JAB SAB KO CHANGE KARNA HO TOH APPLY AND APPLYMAP else REPLACE Q K KEY VALUE PAIR HAI

In [ ]:
#how to change certain values in a row ->pehle loc se value nikalo jo change karni hai then change
#hamesha .lo se karo
filt=df1['first']=='Ali'
#can also change using repalce df['first].replace({'Ahmad':'ali'})
df1.loc[filt,'first']=['Ahmad'] #okay df[filt]['first] it is error cuz it is copy
df1

#now modifying multiple rows
df1['EMAIL']=df1.loc[:,'EMAIL'].str.upper()
df1

In [ ]:
#apply function  on series
def update_email(email):
  return email.lower()
df1['EMAIL']=df1['EMAIL'].apply(update_email)
df1

In [ ]:
#apply function on dataframe
def getLower(series):
  return series.min()
df1.apply(getLower)

In [ ]:
#apply map works only for dataframe
df1=df1.applymap(str.lower)
df1

In [ ]:
#filt = (df1['First Name'] == 'ali') | (df1['First Name'] == 'sara')
#df1.loc[filt, 'First Name'] = ['ALI', 'SARA']
#df1
#ab upar is tarah multiple rows ko set karne mai error araha hai

#Map only works on series and key value pair but assighn other to 0 so replace method is best
df1['email']=df1['email'].replace({'ali.khan@example.com':'ali'})
df1

In [ ]:
df['Hobbyist'].replace({'Yes':'True'})

In [ ]:
# creating and removing columns
#df1['full name']=df1['First Name']+" "+df1['Last Name']
#df1.drop(columns=['First Name','Last Name'],inplace=True)
df1[['first','last']]=df1['full name'].str.split(' ',expand=True)#expand=True compulsory hai
df1

In [ ]:
#Sorting  .sort_values
df1.sort_values(by=['email'])
df['ConvertedComp'].nlargest(10)

57      2000000.0
101     2000000.0
164     2000000.0
434     2000000.0
450     2000000.0
489     2000000.0
537     2000000.0
767     2000000.0
786     2000000.0
1228    2000000.0
Name: ConvertedComp, dtype: float64

In [ ]:
import numpy as np
import pandas as pd

people = {
    'first': ['Corey', 'Jane', 'John', 'Chris', np.nan, None, 'NA'],
    'last': ['Schafer', 'Doe', 'Doe', 'Schafer', np.nan, np.nan, 'Missing'],
    'email': ['CoreyMSchafer@gmail.com', 'JaneDoe@email.com', 'JohnDoe@email.com', None, np.nan, np.nan, np.nan],
    'age': ['33', '55', '63', '36', None, 'Missing', np.nan]
}

df2 = pd.DataFrame(people)
df2

SyntaxError: unmatched '}' (<ipython-input-46-b3127725f678>, line 1)

In [ ]:
#dealing with missing values INDEX;ROW
#df2.dropna(axis='index',how='any',inplace=True) # by default how =any but the problem is that if any value is missing it wil ldelete so i will change how to all
#df2.dropna(axis='index',how='all',inplace=True) # now row with all misswing value will be drop[]
#df2

# acha kabhi kabhi misaal k tor par hume email ko sabse important rakhna toh us column mai agr missing values thab drop karo matlab subsetting
df2.dropna(axis='index',how='all',subset=['email'],inplace=True)
df2

   first     last                    email age
0  Corey  Schafer  CoreyMSchafer@gmail.com  33
1   Jane      Doe        JaneDoe@email.com  55
2   John      Doe        JohnDoe@email.com  63

In [ ]:
#filling
df2.dtypes
#changing age data type pehle hum missing ko np.nan mai karenge q k o float hai
df2['age']=df2['age'].replace({'NA':np.nan,'MISSING':np.nan},inplace=True)
df2['age']=df2['age'].astype(float) #acha agar int mai karenge toh error 1 k np.nan float hai int pe error

<ipython-input-47-294b5a706a9c>:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df2['age']=df2['age'].replace({'NA':np.nan,'MISSING':np.nan},inplace=True)

In [ ]:
df2

   first     last                    email  age
0  Corey  Schafer  CoreyMSchafer@gmail.com  NaN
1   Jane      Doe        JaneDoe@email.com  NaN
2   John      Doe        JohnDoe@email.com  NaN
3  Chris  Schafer                     None  NaN
4    NaN      NaN                      NaN  NaN
5   None      NaN                      NaN  NaN
6     NA  Missing                      NaN  NaN

In [ ]:

#AGGREGATION
#df.median()
#df.describe()
#df.value_counts(normalize=True)

#grouping spliting applying function and combining
country_grp=df.groupby(['Country'])#grouping on country

In [ ]:
#ab is se hume surf 1 country k result milthe hai
filt=df['Country']=='Pakistan'
df.loc[filt,['SocialMedia']].value_counts()

SocialMedia
Facebook       3
LinkedIn       3
WhatsApp       2
Instagram      1
Twitter        1
Name: count, dtype: int64

In [ ]:
#ab is se hume har bar filt nahi run karna parhega
country_grp['SocialMedia'].value_counts().loc['Pakistan']

SocialMedia
Facebook     3
LinkedIn     3
WhatsApp     2
Instagram    1
Twitter      1
Name: count, dtype: int64

In [ ]:
#mean,median
country_grp['ConvertedComp'].agg(['mean','median']).loc['India']

mean      15526.85
median    10287.50
Name: India, dtype: float64

In [ ]:
def pythonx(ser):
  return ser.str.contains('Python').sum()
uses_python=country_grp['LanguageWorkedWith'].apply(pythonx)
uses_python.nlargest(5)

Country
United States     123
India              33
United Kingdom     26
Germany            25
Canada             18
Name: LanguageWorkedWith, dtype: int64